<?php

/**
 * PluginfpPaymentShippingDataTable
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 */
class PluginfpPaymentShippingDataTable extends Doctrine_Table
{
    /**
     * Returns an instance of this class.
     *
     * @return object PluginfpPaymentShippingDataTable
     */
    public static function getInstance()
    {
        return Doctrine_Core::getTable('PluginfpPaymentShippingData');
    }
}