<?php

/**
 * PluginfpPaymentShippingTable
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 */
class PluginfpPaymentShippingTable extends Doctrine_Table
{
    /**
     * Returns an instance of this class.
     *
     * @return object PluginfpPaymentShippingTable
     */
    public static function getInstance()
    {
        return Doctrine_Core::getTable('PluginfpPaymentShipping');
    }
}