fpPaymentShipping:
  columns:
    name: {type: string(50), notnull: true}
    country: {type: string(2), notnull: true}
    state: {type:  string(2)}

fpPaymentShippingData:
  columns:
    shipping_id: {type: integer, notnull: true}
    country: {type: string(2), notnull: true}
    state: {type:  string(2), notnull: true, default: ''}
    standard_price: {type: decimal(10), scale: 2, notnull: true }
    expedited_price: {type: decimal(10), scale: 2 }
  relations:
    Shipping:
      class: fpPaymentShipping
      local: shipping_id
      onDelete: CASCADE
